import { motion } from "framer-motion";
import { ArrowLeft, ExternalLink, Clock } from "lucide-react";
import { format } from "date-fns";
import { useArticle, useArticles } from "@/hooks/use-connect-data";
import { ConnectSectorBadge } from "@/components/connect/ConnectSectorBadge";
import { ConnectSourceBadge } from "@/components/connect/ConnectSourceBadge";
import { ConnectArticleCard } from "@/components/connect/ConnectArticleCard";
import type { AppUser } from "@/types/app";

interface ConnectArticlePageProps {
  articleId?: string;
  onNavigate?: (page: string) => void;
  onArticleClick?: (id: string) => void;
  user?: AppUser | null;
}

export function ConnectArticlePage({ articleId, onNavigate, onArticleClick, user }: ConnectArticlePageProps) {
  const { data: article, isLoading } = useArticle(articleId || "");
  const { data: allArticles } = useArticles(article?.sector);

  if (isLoading) {
    return (
      <div className="min-h-screen pt-20 flex items-center justify-center">
        <div className="h-96 w-full max-w-3xl rounded-xl glass-medium border border-white/10 animate-pulse mx-4" />
      </div>
    );
  }

  if (!article) {
    return (
      <div className="min-h-screen pt-20 flex flex-col items-center justify-center gap-4">
        <h1 className="text-2xl font-bold text-white">Article Not Found</h1>
        <button
          onClick={() => onNavigate?.("connect")}
          className="text-green-400 hover:text-green-300 transition-colors"
        >
          ← Back to Connect
        </button>
      </div>
    );
  }

  const relatedArticles = (allArticles || [])
    .filter((a) => a.id !== article.id)
    .slice(0, 3);

  const sentimentEmoji = article.sentiment === "positive" ? "🟢" : article.sentiment === "negative" ? "🔴" : "🟡";

  return (
    <div className="min-h-screen pt-20">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <button
          onClick={() => onNavigate?.("connect")}
          className="inline-flex items-center gap-2 text-slate-400 hover:text-white mb-8 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Connect
        </button>

        <motion.article initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* Main Card */}
          <div className="glass-medium border border-white/10 rounded-2xl overflow-hidden mb-8">
            {article.image_url && (
              <img
                src={article.image_url}
                alt={article.title}
                className="w-full h-64 md:h-80 object-cover"
              />
            )}

            <div className="p-6 md:p-8">
              <div className="flex items-center gap-3 mb-4 flex-wrap">
                <ConnectSectorBadge sector={article.sector} />
                <ConnectSourceBadge type={article.source_type} />
                <span className="text-xs text-slate-400">
                  {sentimentEmoji} {article.sentiment} sentiment
                </span>
              </div>

              <h1 className="text-2xl md:text-3xl font-black text-white mb-6">
                {article.title}
              </h1>

              <div className="flex items-center gap-4 text-sm text-slate-400 mb-6 flex-wrap">
                <span className="flex items-center gap-1">
                  <Clock className="h-4 w-4" />
                  {format(new Date(article.published_at), "MMMM d, yyyy 'at' h:mm a")}
                </span>
                <span>Source: {article.source_name}</span>
              </div>

              <div className="prose prose-invert max-w-none mb-6">
                <p className="text-slate-300 leading-relaxed text-lg">
                  {article.summary}
                </p>
                <p className="text-sm text-slate-500 italic mt-4">
                  This summary was generated by AI from publicly available sources. For the full story, visit the original source below.
                </p>
              </div>

              <a
                href={article.source_url}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white font-semibold rounded-full transition-all"
              >
                Read Original Source
                <ExternalLink className="h-4 w-4" />
              </a>
            </div>
          </div>

          {/* Article Info Sidebar */}
          <div className="glass-medium border border-white/10 rounded-xl p-6 mb-8">
            <h3 className="text-lg font-bold text-white mb-4">Article Info</h3>
            <dl className="grid grid-cols-2 md:grid-cols-5 gap-4 text-sm">
              <div>
                <dt className="text-slate-500 mb-1">Sector</dt>
                <dd className="text-white capitalize">{article.sector}</dd>
              </div>
              <div>
                <dt className="text-slate-500 mb-1">Region</dt>
                <dd className="text-white">{article.region || "Global"}</dd>
              </div>
              <div>
                <dt className="text-slate-500 mb-1">Source Type</dt>
                <dd className="text-white capitalize">{article.source_type}</dd>
              </div>
              <div>
                <dt className="text-slate-500 mb-1">Sentiment</dt>
                <dd className="text-white">{sentimentEmoji} {article.sentiment}</dd>
              </div>
              <div>
                <dt className="text-slate-500 mb-1">Published</dt>
                <dd className="text-white">{format(new Date(article.published_at), "MMM d, yyyy")}</dd>
              </div>
            </dl>
          </div>

          {/* Related Stories */}
          {relatedArticles.length > 0 && (
            <div className="mb-8">
              <h3 className="text-xl font-bold text-white mb-4">Related Stories</h3>
              <div className="grid md:grid-cols-3 gap-6">
                {relatedArticles.map((a) => (
                  <ConnectArticleCard
                    key={a.id}
                    article={a}
                    onArticleClick={onArticleClick}
                  />
                ))}
              </div>
            </div>
          )}
        </motion.article>
      </div>
    </div>
  );
}
